waypoints:
- point: {x: 5.54028, y: 1.01687, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 12.7217, y: 0.67812, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 18.7424, y: 1.01709, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 24.1998, y: 6.26787, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 28.5279, y: 9.91822, z: 0, vel: 1, rad: 0.8, stop: true}
- point: {x: 40.8917, y: 18.6359, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 47.6045, y: 13.4797, z: 0, vel: 1, rad: 0.8, stop: true}
- point: {x: 55.8581, y: 1.43388, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 60.0608, y: -5.03815, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 63.1514, y: -9.29613, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 69.2647, y: -18.9718, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 75.7432, y: -24.5216, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 79.7408, y: -28.3171, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 84.1298, y: -32.2889, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 88.845, y: -36.2453, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 94.3163, y: -40.3713, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 98.6156, y: -43.6164, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 100.427, y: -46.3712, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 102.991, y: -48.7654, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 106.707, y: -51.8993, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 116.932, y: -56.2026, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 121.715, y: -58.9792, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 128.852, y: -56.4864, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 132.475, y: -50.5942, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 136.324, y: -44.3, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 140.457, y: -38.5531, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 144.721, y: -32.7546, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 148.667, y: -26.4539, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 152.658, y: -20.4025, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 156.981, y: -14.7734, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 161.252, y: -8.93902, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 165.563, y: -3.21735, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 169.996, y: 2.8545, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 173.871, y: 8.40251, z: 0, vel: 1, rad: 0.8, stop: true}
- point: {x: 178.093, y: 14.7491, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 182.083, y: 20.4354, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 187.028, y: 26.0844, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 191.189, y: 31.9199, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 195.228, y: 38.0132, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 199.077, y: 43.8881, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 203.158, y: 50.071, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 207.028, y: 55.9916, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 210.881, y: 62.1243, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 214.286, y: 68.3365, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 218.887, y: 70.9631, z: 0, vel: 1, rad: 0.8, stop: true}
- point: {x: 222.478, y: 76.429, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 224.283, y: 79.3506, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 227.868, y: 85.3665, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 227.635, y: 89.9449, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 222.513, y: 93.112, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 215.21, y: 98.234, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 209.484, y: 102.401, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 203.496, y: 106.83, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 197.245, y: 110.748, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 191.714, y: 115.084, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 186.589, y: 118.549, z: 0, vel: 1, rad: 0.8, stop: false}
finish_pose:
  header: {seq: 0, stamp: 1698980872.10818, frame_id: map}
  pose:
    position: {x: 180.816, y: 124.3, z: 0}
    orientation: {x: 0.0, y: 0.0, z: 0.9749242329362375, w: 0.22253705317022807}